sudo: false
language: node_js
node_js:
  - 10
cache: yarn
branches:
  only:
    - master
script:
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: public